apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: docker-build
spec:
  description: This pipeline is ideal for building container images from a Containerfile while reducing network traffic.
  params:
    - name: git-url
      type: string
      description: Source Repository URL
    - name: revision
      type: string
      description: Revision of the Source Repository
    - name: output-image
      type: string
      description: Fully Qualified Output Image
    - name: path-context
      type: string
      default: .
      description: Path to the source code of an application's component from where to build image.
    - name: dockerfile
      type: string
      default: Dockerfile
      description: Path to the Dockerfile inside the context specified by parameter path-context
    - name: rebuild
      type: string
      default: "false"
      description: Force rebuild image
    - name: skip-checks
      type: string
      default: "false"
      description: Skip checks against built image
    - name: hermetic
      type: string
      default: "false"
      description: Execute the build with network isolation
    - name: prefetch-input
      type: string
      default: ""
      description: Build dependencies to be prefetched by Cachi2
    - name: image-expires-after
      type: string
      default: ""
      description: Image tag expiration time, time values could be something like 1h, 2d, 3w for hours, days, and weeks, respectively.
    - name: build-image-index
      type: string
      default: "true"
      description: Add built image into an OCI image index
    - name: build-args
      type: array
      default: []
      description: Array of --build-arg values ("arg=value" strings) for buildah
  tasks:
    # Init
    - name: init
      params:
        - name: image-url
          value: $(params.output-image)
        - name: rebuild
          value: $(params.rebuild)
        - name: skip-checks
          value: $(params.skip-checks)
      taskRef:
        params:
          - name: name
            value: init
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-init:0.2@sha256:7a24924417260b7094541caaedd2853dc8da08d4bb0968f710a400d3e8062063
          - name: kind
            value: task
        resolver: bundles
    # Clone repository
    - name: clone-repository
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.revision)
      runAfter:
        - init
      taskRef:
        params:
          - name: name
            value: git-clone
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-git-clone:0.1@sha256:3ced9a6b9d8520773d3ffbf062190515a362ecda11e72f56e38e4dd980294b57
          - name: kind
            value: task
        resolver: bundles
      when:
        - input: $(tasks.init.results.build)
          operator: in
          values:
            - "true"
      workspaces:
        - name: output
          workspace: workspace
    # Prefetch dependencies
    - name: prefetch-dependencies
      params:
        - name: input
          value: $(params.prefetch-input)
      runAfter:
        - clone-repository
      taskRef:
        name: prefetch-dependencies
      workspaces:
        - name: source
          workspace: workspace
    # Build container
    - name: build-container
      params:
        - name: IMAGE
          value: $(params.output-image)
        - name: DOCKERFILE
          value: $(params.dockerfile)
        - name: CONTEXT
          value: $(params.path-context)
        - name: HERMETIC
          value: $(params.hermetic)
        - name: PREFETCH_INPUT
          value: $(params.prefetch-input)
        - name: IMAGE_EXPIRES_AFTER
          value: $(params.image-expires-after)
        - name: COMMIT_SHA
          value: $(tasks.clone-repository.results.commit)
        - name: BUILD_ARGS
          value: $(params.build-args[*])
      runAfter:
        - prefetch-dependencies
      taskRef:
        params:
          - name: name
            value: buildah
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-buildah:0.4@sha256:c777fdb0947aff3e4ac29a93ed6358c6f7994e6b150154427646788ec773c440
          - name: kind
            value: task
        resolver: bundles
      when:
        - input: $(tasks.init.results.build)
          operator: in
          values:
            - "true"
      workspaces:
        - name: source
          workspace: workspace
    # Build image index
    - name: build-image-index
      params:
        - name: IMAGE
          value: $(params.output-image)
        - name: COMMIT_SHA
          value: $(tasks.clone-repository.results.commit)
        - name: IMAGE_EXPIRES_AFTER
          value: $(params.image-expires-after)
        - name: ALWAYS_BUILD_INDEX
          value: $(params.build-image-index)
        - name: IMAGES
          value:
            - $(tasks.build-container.results.IMAGE_URL)@$(tasks.build-container.results.IMAGE_DIGEST)
      runAfter:
        - build-container
      taskRef:
        params:
          - name: name
            value: build-image-index
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-build-image-index:0.1@sha256:462ecbf94ec44a8b770d6ef8838955f91f57ee79795e5c18bdc0fcb0df593742
          - name: kind
            value: task
        resolver: bundles
      when:
        - input: $(tasks.init.results.build)
          operator: in
          values:
            - "true"
  finally:
    # Show SBOM
    - name: show-sbom
      params:
        - name: IMAGE_URL
          value: $(tasks.build-image-index.results.IMAGE_URL)
      taskRef:
        params:
          - name: name
            value: show-sbom
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-show-sbom:0.1@sha256:002f7c8c1d2f9e09904035da414aba1188ae091df0ea9532cd997be05e73d594
          - name: kind
            value: task
        resolver: bundles
  workspaces:
    - name: workspace
